# docker-compose.yml
version: "3.8"

services:
  qdrant:
    image: qdrant/qdrant:v1.9.0
    container_name: core_qdrant_db
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant-data:/qdrant/storage # Use a named volume for persistence
    restart: always

  # Define the named volumes for data persistence
volumes:
  qdrant-data:
